- back-end/api-server/package-lock.json
- back-end/api-server/package.json
- back-end/api-server/src/index.ts
- back-end/api-server/tsconfig.json
- typescript 적용 후  index.ts 기본파일 생성
- tsconfig.json 파일 추가
- package.json에 nodemon 명령어 추가
back-end/api-server express에 typescript 적용
#100
- package.json 수정 (nodemon, typescript, ts-node 등)
- tsconfig.json 파일 생성 (명령어 : npx tsc --init)
app.js를 지워야 할지
> 🛠 : typescript를 사용하기 위한 express 세팅(api-server)

- front-end/src/App.scss
- front-end/src/layout/AppbarLayout/index.tsx
- front-end/src/layout/AppbarLayout/style.scss
- front-end/src/pages/LobbyPage/style.scss
> 💄 : 로비 화면 스타일 버그 수정

- back-end/api-server/database/connect.ts
- back-end/socket-server/package-lock.json
- back-end/socket-server/package.json
- back-end/socket-server/src/index.ts
- back-end/socket-server/tsconfig.json
- api-server 데이터베이스 연동 부분 PORT 옵션 추가
- socket-server index.ts 생성 및 tsconfig 추가
> api-server 데이터베이스 연동 부분 수정 및 socket-server 설정

- back-end/api-server/database/query.ts
- back-end/api-server/routes/index.js
- back-end/api-server/routes/rankSearch.ts
- back-end/api-server/routes/users.js
- back-end/api-server/src/index.ts
- front-end/src/App.tsx
- front-end/src/pages/RankPage/index.tsx
- front-end/src/pages/RankPage/style.scss
[랭킹] 구현 마무리
1. 등수, 아이디 등 정보 데이터 Api 요청
2. 분류, 모드 버튼 누를 때 마다 fetch
3. 왼쪽 프로필 정보 보이기, 플레이어 닉네임 입력 후 검색 가능
4. 선택한 분류에 따라 표에 content 랜더링, 표 header 고정
> [랭킹] 구현 마무리

- back-end/socket-server/services/tetrisSocket.ts
- front-end/src/components/Tetris/Board/index.tsx
테트리스 멀티 게임 버그 수정
- 블록을 심하게 움직일 경우 오류 발생 수정
- 게임 오버된 플레이어에게 공격 블록이 전달되던 현상 수정
- 불필요한 주석 제거
> 테트리스 멀티 게임 버그 수정

- front-end/src/pages/LoginPage/index.tsx
> 로그인 된 상태라면 로비로 이동

- back-end/api-server/routes/auth.ts
- front-end/src/common/styles/_base.scss
- front-end/src/components/Modal/index.tsx
- front-end/src/components/Modal/style.scss
- front-end/src/pages/LobbyPage/index.tsx
- front-end/src/pages/LobbyPage/style.scss
친구 요청 알림등을 포함한 모달에 대한 UI 작업입니다.
#148
> 알림센터 모달 작업

- back-end/api-server/routes/friend.ts
- back-end/api-server/services/friend.ts
친구 요청 관련 작업
1. 클라이언트로부터 oauth_id 를 받는 것에서 nickname을 받는 것으로 내부작업 완료
2. 서버에서 수정된건, 쿼리 부분. DB에는 oauth_id가 기록되고, 그것과 별개로 수정한 작업은 슬렉으로 공유 완료
3. get 요청으로 변경
```
GET /api/friend/request-list
key값 : requestee
```
```
GET /api/friend/list
key값 : nickname
```
> [친구 요청] 내부 쿼리 수정, post->get 수정 등 작업 완료했습니다.

- back-end/api-server/database/query.ts
- back-end/api-server/routes/friend.ts
- back-end/api-server/services/friend.ts
- back-end/api-server/src/index.ts
- front-end/src/pages/RankingPage/index.tsx
친구인 상태에서 다시 친구요청 보냈을때 처리 완료.
1. 내가 나한테 친구 요청 보내는 경우 처리
2. 친구인 상태에서 다시 친구요청 보냈을때 처리.
> [친구 요청] 이미 친구인 상태에서 친구 요청 보냈을때의 처리 완료했습니다.

- front-end/src/pages/ProfilePage/index.tsx
상대방의 profile에서도 edit이 되는 것을 막음
>  🐛 : 상대방의 profile에서도 edit이 되는 것을 막음

- back-end/api-server/routes/rankingSearch.ts
- front-end/src/pages/RankingPage/index.tsx
- play테이블에 nickname에서 oauth_id으로 수정됨에 따라, 쿼리 문 수정
- 테스트 완료 !
> 🐛 : 랭킹 페이지 버그 수정

- back-end/api-server/routes/gameRecord.ts
- back-end/api-server/services/gameRecord.ts
- back-end/api-server/src/index.ts
- back-end/socket-server/services/tetrisSocket.ts
[게임 종료 시] api-server와 연결
- 게임 종료 시 결과 데이터베이스에 기록
> [게임 종료 시] api-server와 연결

- back-end/socket-server/package-lock.json
- back-end/socket-server/package.json
- back-end/socket-server/services/tetrisSocket.ts
- back-end/socket-server/src/index.ts
- back-end/socket-server/utils/dateUtil.ts
- back-end/socket-server/utils/tetrisUtil.ts
- front-end/src/components/Tetris/Board/index.tsx
- front-end/src/components/Tetris/OtherBoard/index.tsx
- front-end/src/pages/GamePage/index.tsx
테트리스 소켓 코드 리팩토링 및 버그 수정
- tetrisSocket.ts 리팩토링
- 테트리스 게임 시 블록 이동 속도 향상
- 게임 종료 후 다른 플레이어가 게임 종료되면 결과 창이 다시 뜨는 현상
>  테트리스 소켓 코드 리팩토링 및 버그 수정

- back-end/api-server/routes/auth.ts
- back-end/api-server/routes/friend.ts
- back-end/api-server/services/friend.ts
- back-end/socket-server/services/lobbyUserSocket.ts
- back-end/socket-server/type/socketType.ts
- back-end/socket-server/utils/userUtil.ts
- front-end/src/components/UserPopper/index.tsx
- front-end/src/context/SocketContext.tsx
- front-end/src/features/friend/friendAPI.ts
- front-end/src/features/friend/friendSlice.ts
- front-end/src/features/socket/socketSlice.ts
- front-end/src/pages/LobbyPage/index.tsx
> Oauth ID  기반으로 친구 요청 / 수락 / 조회 기능 이관

- back-end/api-server/routes/profile.ts
- front-end/src/components/Popper/style.scss
- front-end/src/components/UserPopper/index.tsx
- front-end/src/context/SocketContext.tsx
- front-end/src/pages/ProfilePage/index.tsx
닉네임 변경 시 생기는 오류 수정했습니다
#172 
1. 닉네임 변경 후, 로비로 돌아갔을 때 접속자 목록에 반영되도록
2. 닉네임 변경 후, 게임방에 입장 했을 때, 적용안되는 오류 수정
3. 친구 추가 버튼을 눌러도 popper가 꺼지지 않는 것 수정
1. 친구 목록에 반영되도록 하는 것도 추가해서 다음 PR로 올리겠습니다 ^_^
> 닉네임 변경 시 생기는 오류 수정

- back-end/api-server/build/swagger.yaml
- back-end/api-server/package-lock.json
- back-end/api-server/package.json
- back-end/api-server/routes/friend.ts
- back-end/api-server/src/index.ts
Swagger Api 명세 작업
1. yaml 파일에 api들 명세
2. example과 model 나눠서 작성
> Swagger Api 명세 작업

- back-end/api-server/routes/rankingSearch.ts
> 🐛 : [랭킹]테이블명 대문자로 수정

- front-end/src/components/Modal/index.tsx
- front-end/src/components/Tetris/Board/index.tsx
- front-end/src/constants/tetris.ts
- front-end/src/pages/GamePage/index.tsx
- front-end/src/pages/GamePage/style.scss
게임방 키 입력 버그 수정
- 블록 홀드, 블록 왼쪽 방향으로 돌리기 한글 입력시 동작 안하던 현상 수정
- 게임 진행하면서 채팅이 잘 안쳐지던 현상 수정
- 게임 종료 시 게임 결과 테이블에 x 표시 추가
> 게임방 키 입력 버그 수정

- back-end/api-server/routes/api-routes/profile.ts
- front-end/src/components/InfiniteScroll/index.tsx
- front-end/src/components/InfiniteScroll/style.scss
- front-end/src/pages/ErrorPage/constants.ts
- front-end/src/pages/ProfilePage/index.tsx
- front-end/src/pages/ProfilePage/profileFetch.tsx
- front-end/src/pages/ProfilePage/style.scss
- front-end/src/pages/RankingPage/index.tsx
- front-end/src/pages/RankingPage/rankFetch.tsx
- 최근 전적에서 시간대를 맞춰줌
- 에러 페이지에 있는 오타를 지움
- useEffect에 clean up을 걸어줌
#195
> 프로필 페이지, 에러 페이지에 있는 버그를 수정

- back-end/api-server/package-lock.json
- back-end/socket-server/package-lock.json
- back-end/socket-server/package.json
- back-end/socket-server/services/lobbyUserSocket.ts
- back-end/socket-server/services/socket.ts
- back-end/socket-server/services/tetrisSocket.ts
- back-end/socket-server/src/index.ts
- back-end/socket-server/utils/tetrisUtil.ts
- back-end/socket-server/utils/userUtil.ts
- front-end/src/context/SocketContext.tsx
- front-end/src/pages/GamePage/index.tsx
- front-end/src/pages/LobbyPage/index.tsx
소켓 서버의 PORT를 분리하여 복수의 서버에서 부하를 분산할 수 있도록 변경했고 각 서버간 소켓 정보는 socket.io의 redis-adapter를 활용했습니다.
그 외의 자잘한 소켓 관련 버그 픽스했습니다.
이 PR 기준으로 각자 개발 환경에서 redis가 필요할텐데 아직 별도의 dockerfile을 마련하지는 못헀고, 6379 포트에 레디스를 띄워주시면 로컬에서 테스트 가능합니다.
> Redis로 연결한 결과 이긴합니다.

- front-end/public/index.html
- front-end/src/pages/LoginPage/index.tsx
lighthoust accessibility 향상
- naver 로그인 버튼 height 수정
- CSP 적용
> lighthoust accessibility 향상

- front-end/craco.config.js
- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.tsx
- front-end/src/components/Modal/style.scss
- front-end/src/layout/AppbarLayout/index.tsx
- front-end/src/pages/LoginPage/index.tsx
> 코드 스플리팅 등 성능 최적화한 것들

- front-end/src/pages/RankingPage/style.scss
> [랭킹] css 마무리

- .github/workflows/deploy.yml
- deploy.sh
> [develop] merge to main
